Hello Microverse project
muhammedb8826/Hello-world pull request #3
Opened 2023-01-11 19:48 UTC by muhammedb8826

I have added three files index.html, style.css, and test.dm
I have installed lineters and stylelint packages for the project

2023-01-11 20:11 UTC, levy002 requested changes
## Hello @muhammedb8826   , :wave:
### I'm Levy, your PR reviewer

Good job so far :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)

## Status: REQUIRED CHANGES ♻️
_Check the comments under the review._

- [x] Kindly make the `test.md` file ignored by git so it must not be represented in the repo and it must be presented in `gitignore` file. :wink:  

- [ ] Kindly make sure to update a README file by copying the [Microverse README template](https://github.com/microverseinc/readme-template/blob/master/README.md) and make sure to customize it according to your project. :wink: 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [OPTIONAL] Kindly make sure only next time the changes you made must be in the `feature` branch and must be not represented In the `main` branch until it's merged.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @levy002 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-11 20:47 UTC, muhammedb8826 commented
Thank you so much

On Wed, Jan 11, 2023 at 11:11 PM levy_ukwishaka ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> Hello @muhammedb8826 <https://github.com/muhammedb8826> , 👋 I'm Levy,
> your PR reviewer
>
> Good job so far 👍
> There are some issues that you still need to work on to go to the next
> project but you are almost there!
>
>
> <https://camo.githubusercontent.com/77566116408d88259ddadf7605a02b67a4e825e002a39682ca5f2e8bca8c4d64/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966>
> Status: REQUIRED CHANGES ♻️
>
> *Check the comments under the review.*
>
>    -
>
>    Kindly make the test.md file ignored by git so it must not be
>    represented in the repo and it must be presented in gitignore file. 😉
>    -
>
>    Kindly make sure to update a README file by copying the Microverse
>    README template
>    <https://github.com/microverseinc/readme-template/blob/master/README.md>
>    and make sure to customize it according to your project. 😉
>
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you to take them
> into account as they can make your code better.*
>
>    - [OPTIONAL] Kindly make sure only next time the changes you made must
>    be in the feature branch and must be not represented In the main
>    branch until it's merged.
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me @levy002 <https://github.com/levy002> in your
> question so I can receive the notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/muhammedb8826/Hello-world/pull/3#pullrequestreview-1244545381>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3S6YHJY7RRETR6CB5CWACDWR4HX7ANCNFSM6AAAAAATYNOYOA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-01-12 08:31 UTC, Olamarx requested changes
Hi @muhammedb8826, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
<img src="https://media0.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif"/>

 ## Highlights
- Linters passed ✔️
- GitHub flow ✔️ 

 ## Required Changes ♻️
_Check the comments under the review._
- [ ] I would advise you to use a well-detailed readme file template provided by Microverse, it would help you and the visitors to understand what the repo entails at a glance. You can copy the file [here](https://github.com/microverseinc/readme-template) and adapt it to your own. Emphasis on adapt it to your own, dont remove any section, just replace them all to fit your project.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-12 15:10 UTC, Felix45 approved these changes
# Approved :green_circle: 
Hi @muhammedb8826  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://camo.githubusercontent.com/af3e249aed483b04a88ff676e872d6926cd426af8a3e008290d32ec69f576ae9/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f69337133367a454653684331386f533676302f67697068792e676966" />

## Highlights :heavy_check_mark: 
- [ ] Implemented all the changes from the previous reviewer :heavy_check_mark: 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-12 15:10 UTC, Felix45 commented on README.md
> +For stylelint errors run:<code>sudo npx stylelint "**/*.{css,scss}" --fix</code> for automatic fix.
- [ Optional ] The `Getting Started` section of your readme file is very important, this means you always have to fill it correctly. Please see an example of how I would fill in this section in my `readme` file, the instructions you give in the `readme` file should always be clear and easy for someone to follow.

<!-- GETTING STARTED -->

## 💻 Getting Started <a name="getting-started"></a>

To get a local copy up and running, follow these steps.

```sh
   git clone git@github.com:muhammedb8826/Hello-world.git
```

### Prerequisites

In order to run this project you need:
 - NodeJS
 - Browser

### Setup

Clone this repository to your desired folder:

<!--
Example commands:
-->

```sh
  git clone git@github.com:muhammedb8826/Hello-world.git
  cd Hello-World
```

### Install

Install project dependencies in this project with:

```sh
  npm install
```

### Usage

To run the project, open the project with live server and visit [http://localhost:5500](http://localhost:5500)

### Open in browser

http://localhost:5500

2023-01-12 15:25 UTC, muhammedb8826 commented
Awesome, thank you so much!

On Thu, Jan 12, 2023 at 6:10 PM Felix Ouma ***@***.***> wrote:

> ***@***.**** approved this pull request.
> Approved 🟢
>
> Hi @muhammedb8826 <https://github.com/muhammedb8826>
>
> Your project is complete! There is nothing else to say other than... it's
> time to merge it [image: :shipit:]
> Congratulations! 🎉
>
>
> <https://camo.githubusercontent.com/af3e249aed483b04a88ff676e872d6926cd426af8a3e008290d32ec69f576ae9/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f69337133367a454653684331386f533676302f67697068792e676966>
> Highlights ✔️
>
>    - Implemented all the changes from the previous reviewer ✔️
>
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix won't stop the approval of this
> PR. However, I strongly recommend you to take them into account as they can
> make your code better. Some of them were simply missed by the previous
> reviewer and addressing them will really improve your application.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In README.md
> <https://github.com/muhammedb8826/Hello-world/pull/3#discussion_r1068238015>
> :
>
> > +## Getting Started
>
> +
>
> +Clone the folder to your local machine by using ,(https://github.com/muhammedb8826/Hello-world.git) link
>
> +
>
> +### Prerequisites
>
> +
>
> +### Setup
>
> +Set up the yaml file located in <code>.github/workflows/linters.yml</code>
>
> +
>
> +### Install
>
> +Install all different dependencies of linters file:
>
> +- lighthouse (<code>.github/workflows/linters.yml</code>)
>
> +- webhint (<code>.github/workflows/linters.yml</code>)
>
> +- stylelint (<code>.github/workflows/linters.yml</code>)
>
> +
>
> +### Run tests
>
> +After pushing the changes on github, merge your pull request and let github action process changes.
>
> +
>
> +### Deployment
>
> +Check for the tests when you generate a pull request and fix errors, if any.
>
> +For stylelint errors run:<code>sudo npx stylelint "**/*.{css,scss}" --fix</code> for automatic fix.
>
>
>
>    - [ Optional ] The Getting Started section of your readme file is very
>    important, this means you always have to fill it correctly. Please see an
>    example of how I would fill in this section in my readme file, the
>    instructions you give in the readme file should always be clear and
>    easy for someone to follow.
>
> 💻 Getting Started
>
> To get a local copy up and running, follow these steps.
>
>    git clone ***@***.***:muhammedb8826/Hello-world.git
>
> Prerequisites
>
> In order to run this project you need:
>
>    - NodeJS
>    - Browser
>
> Setup
>
> Clone this repository to your desired folder:
>
>   git clone ***@***.***:muhammedb8826/Hello-world.git
>
>   cd Hello-World
>
> Install
>
> Install project dependencies in this project with:
>
>   npm install
>
> Usage
>
> To run the project, open the project with live server and visit
> http://localhost:5500
> Open in browser
>
> http://localhost:5500
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/muhammedb8826/Hello-world/pull/3#pullrequestreview-1245783135>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3S6YHIY56QQLLVJEJXVC23WSANFXANCNFSM6AAAAAATYNOYOA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-01-13 19:20 UTC, merged